apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prept-ingress
  namespace: prept
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: prept.local
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: prept-backend
                port:
                  number: 8080
          - path: /
            pathType: Prefix
            backend:
              service:
                name: prept-frontend
                port:
                  number: 80
